# Generated by Django 2.1.5 on 2019-01-31 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_imgae'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imgae',
            new_name='image',
        ),
    ]
