# Generated by Django 2.1.5 on 2019-01-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0002_surv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surv',
            old_name='content',
            new_name='content1',
        ),
        migrations.AddField(
            model_name='surv',
            name='content2',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surv',
            name='content3',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
