# Generated by Django 2.1.5 on 2019-01-30 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0003_auto_20190130_0747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='title',
        ),
    ]
